OOP - Milestone: instructions for players
julian3493/Ruby_TicTacToe pull request #5
Opened 2020-10-23 15:10 UTC by julian3493

### Instructions in the README file

- We write detailed instructions for each step into the game.
- We give instructions to start the game
- We explain how the Tic Tac Toe game works

2020-10-23 18:39 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [x] Let's write detailed steps on how to clone and run the project locally 

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-10-23 20:42 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [ ] Let's write detailed steps on how to clone and run the project locally, for example

````ruby
Clone the repository to your local machine
$ git clone https://github.com/kobiyoyo/Tic-Tac-Toe.git
Go to the directory

$ cd tic-tac-toe
Go to the execution file directory

$ cd bin
Run the file

$ ruby main.rb
````

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-10-24 01:37 UTC, euqueme approved these changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @julian3493 and @mke2111 :lollipop: :balloon: 

### Thank you for working on the changes requested by the previous reviewer, :medal_sports: :medal_sports:  your Readme file looks way better and your game works just fine :ok_hand: it's a yes for me Congratulations merge this branch and keep going :tada: :tada: :tada: 

### Please :pray: keep up the good work :clinking_glasses: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-10-24 01:37 UTC, euqueme commented on README.md
> +- Open your terminal and go to the directory where you want to clone the repo.
### [OPTIONAL]

- [ ] Users don't necessarily need to clone the repo they can just download it too, let's mention this somewhere

2020-10-24 01:38 UTC, merged